services:
    import.factory:
        class: ImportBundle\Factory\ImportFactory
        arguments:
    import.service:
        class: ImportBundle\Services\ImportService
        arguments:
            - "@import.factory"
            - "@doctrine.orm.default_entity_manager"
            - "@validator"
            - "plain_value"
#parameters:
#    entity: "ImportBundle:ProductItem"

